baseURL = "https://tcd.lol"
languageCode = "en-us"
title = "Clay's Blog"
theme = "ananke"
pygmentsCodefences = true
pygmentsStyle = "monokai"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # favicon = ""
  # facebook = ""
  # twitter = ""
  instagram = "https://www.instagram.com/claydunston/"
  github = "https://github.com/dunstontc"
  # gitlab = ""
  # linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
